# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalculatorForPPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalculatorForPPI
  pod 'IQKeyboardManagerSwift'

  target 'CalculatorForPPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalculatorForPPIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
